In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
%matplotlib inline

## **1. Create a class to standardardize (subtract the mean and divide by standard deviation) an input padas dataframe**

In [2]:
file_path = Path("stocks_closing_value_2018.csv")
tech_stocks = pd.read_csv(file_path, index_col='Date', parse_dates=True)
tech_stocks.head()

AAPL       MSFT         GOOG          FB         AMZN
Date                                                                   
2018-01-02  168.339050  84.128128  1065.000000  181.419998  1189.010010
2018-01-03  168.309738  84.519646  1082.479980  184.669998  1204.199951
2018-01-04  169.091522  85.263542  1086.400024  184.330002  1209.589966
2018-01-05  171.016678  86.320648  1102.229980  186.850006  1229.140015
2018-01-08  170.381485  86.408737  1106.939941  188.279999  1246.869995

In [3]:
df = pd.DataFrame(tech_stocks)
df.head()

AAPL       MSFT         GOOG          FB         AMZN
Date                                                                   
2018-01-02  168.339050  84.128128  1065.000000  181.419998  1189.010010
2018-01-03  168.309738  84.519646  1082.479980  184.669998  1204.199951
2018-01-04  169.091522  85.263542  1086.400024  184.330002  1209.589966
2018-01-05  171.016678  86.320648  1102.229980  186.850006  1229.140015
2018-01-08  170.381485  86.408737  1106.939941  188.279999  1246.869995

In [4]:
# calculating mean of each stocks
mean_value = pd.DataFrame.mean(df)
mean_value

AAPL     186.268993
MSFT      99.803780
GOOG    1113.225134
FB       171.510956
AMZN    1641.726176
dtype: float64

In [5]:
# Calculating Standard Deviation 
std_dev = pd.DataFrame.std(df)
std_dev

AAPL     20.712947
MSFT      8.231386
GOOG     67.315548
FB       19.977452
AMZN    197.275076
dtype: float64

In [6]:
#Normalizationing the each data point 
norm_data = df -df.mean()
norm_data.head()

AAPL       MSFT       GOOG         FB        AMZN
Date                                                              
2018-01-02 -17.929943 -15.675651 -48.225134   9.909042 -452.716166
2018-01-03 -17.959255 -15.284134 -30.745154  13.159042 -437.526225
2018-01-04 -17.177471 -14.540237 -26.825110  12.819046 -432.136210
2018-01-05 -15.252315 -13.483131 -10.995154  15.339050 -412.586161
2018-01-08 -15.887508 -13.395042  -6.285193  16.769043 -394.856181

In [7]:
final_norm = norm_data / std_dev
final_norm.head(10)

AAPL      MSFT      GOOG        FB      AMZN
Date                                                        
2018-01-02 -0.865639 -1.904376 -0.716404  0.496011 -2.294847
2018-01-03 -0.867055 -1.856812 -0.456732  0.658695 -2.217848
2018-01-04 -0.829311 -1.766438 -0.398498  0.641676 -2.190526
2018-01-05 -0.736366 -1.638015 -0.163338  0.767818 -2.091426
2018-01-08 -0.767033 -1.627313 -0.093369  0.839399 -2.001551
2018-01-09 -0.767976 -1.634447 -0.103470  0.818875 -1.971999
2018-01-10 -0.769864 -1.682012 -0.157692  0.817374 -1.963736
2018-01-11 -0.723155 -1.651096 -0.114463  0.813870 -1.850442
2018-01-12 -0.637760 -1.470349  0.134217  0.393395 -1.705873
2018-01-16 -0.680221 -1.618989  0.126789  0.344340 -1.707596

## **a. Implement a fit model**

## I am going to create an arrary to demonstrate a fit and transform method

In [8]:
# importing SK-learn library which is super handy tool to perfrom fit & transform method

from sklearn.preprocessing import StandardScaler


In [9]:
# Creating an array

example = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [10]:
# Ceating an object

standscaler = StandardScaler()

In [11]:
#Fitting with a mean value

standscaler.fit(example)

StandardScaler(copy=True, with_mean=True, with_std=True)

## **b. Implement a transform method** 

In [12]:
# Normalizating the data set
standscaler.transform(example)

array([[-1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487]])

## **Implementing Fit and transform model in single function**

In [13]:
## We can perform fir and transform in single function as well  

x_scaler = standscaler.fit_transform(example)
print(x_scaler)

[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


## **C. Implement an inverse transform method**

## Here, I am creating new array with some random numbers to demonstrate reverse tranformation.

In [14]:
# Import sklearn library 

from sklearn import preprocessing
StandardScaler = preprocessing.StandardScaler()

In [15]:
example_2 = np.array([[-400, 25, -125],
             [-100, 10, 145],
             [0, 0, 0],
             [100, 78, -108],
             [400, 15, 1]])
example_2

array([[-400,   25, -125],
       [-100,   10,  145],
       [   0,    0,    0],
       [ 100,   78, -108],
       [ 400,   15,    1]])

In [16]:
x_scaler = StandardScaler.fit_transform(example_2)
print(x_scaler)

[[-1.53392998 -0.0218879  -1.11216386]
 [-0.38348249 -0.5690854   1.67858189]
 [ 0.         -0.93388373  0.17984806]
 [ 0.38348249  1.91154327 -0.93645024]
 [ 1.53392998 -0.38668623  0.19018415]]


In [17]:
x_scaledback = StandardScaler.inverse_transform(x_scaler)
print(x_scaledback)

[[-400.   25. -125.]
 [-100.   10.  145.]
 [   0.    0.    0.]
 [ 100.   78. -108.]
 [ 400.   15.    1.]]


##  I didn't quite understand Q.N.2. Maybe above code already answered it. I am not too sure what "unit test" means. I guess it referring to a piece of code which can universally apply to different dataset to obtain similar result.

## **3. Write a function that preprocesses a given string:**
 

In [22]:
# Importing NLP library

import nltk 
nltk.download('punkt')
import string 
import re 

[nltk_data] Error loading punkt: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>


In [23]:
# Input Text

text = """"
William Shakespeare was born in Stratford-upon-Avon on April 23, 1564 to his parents Mary Arden and John Shakespeare. Shakespeare was the third child of eight. He was the oldest surviving son, because in the time Shakespeare was born there was a plague going around called the Bubonic Plague. This is also known as Black Death because it killed so many people in the middle ages. It supposedly killed about one out of every seven people. Not very much is known about Shakespeare’s early years in life, the only way historians found about his early life were based on church records, and court settlements. It was thought that Shakespeare got his education at a grammar school called King Edward VI School Stratford-upon-Avon. When Shakespeare was eighteen, he married a woman who was eight years older than him, her name was Anne Hathaway. Together they had three children. The first was a girl named Susanna and then two years later they had twins, one boy name Hamnet and a daughter named Judith. Hamnet died at the age of 11 of unknown causes. After the death of Shakespeare’s only son supposedly Shakespeare was never the same. Historians have no clue what happened in Shakespeare’s life between the years of 1585-1592. Historians call this time of his life the “lost years.” No one is really sure when Shakespeare started writing but they think it was in 1592 when some of his plays were starting to be performed on stage in London.

Shakespeare has had a lot of numerous plays and almost all of them were performed in his time. Some of his first works include Richard III and parts of Henry VI. No one really knows when a lot of Shakespeare’s plays were written, but most historians think it was sometime in the early 1590s. Shakespeare has two really famous narrative poems that many people read today, Hamlet and Romeo and Juliet.

Hamlet was first printed in 1601 and could possibly be one of Shakespeare’s most famous stories. This story is pretty much about Prince Hamlet planning revenge on Claudius for murdering King Hamlet. When he does kill Claudius he takes over the throne of his father. One of the most famous quotes from the book Hamlet written by Shakespeare is, “To be or not to be that is the question: Whether ’tis nobler in the mind to suffer, the slings and arrows of outrageous fortune, Or to take arms against a sea of troubles and by opposing, end them.” This is Shakespeare’s longest narrative poem, and maybe one of his most tragic, but the story Romeo and Juliet is right up there with Hamlet.

Romeo and Juliet is a story that everyone in their life is going to read, especially in high school. If you ask people that have graduated from high school, what book they remember reading. I guarantee you that most of them will mention Romeo and Juliet. That just shows you how powerful Shakespeare’s writings are. The story Romeo and Juliet is about two people who become to love each other but where they come from, they are truly enemies. It is dramatic irony because since they cannot be together, but they love each other so much, they end up killing themselves together. Romeo and Juliet is to me one of his greatest pieces of work. 
"""

## a. Tokenize the text 

In [24]:
from nltk.corpus import stopwords
nltk.download('stopwords')
from nltk.tokenize import word_tokenize

[nltk_data] Error loading stopwords: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>


In [25]:
token_list = word_tokenize(text)
print(token_list)

['``', 'William', 'Shakespeare', 'was', 'born', 'in', 'Stratford-upon-Avon', 'on', 'April', '23', ',', '1564', 'to', 'his', 'parents', 'Mary', 'Arden', 'and', 'John', 'Shakespeare', '.', 'Shakespeare', 'was', 'the', 'third', 'child', 'of', 'eight', '.', 'He', 'was', 'the', 'oldest', 'surviving', 'son', ',', 'because', 'in', 'the', 'time', 'Shakespeare', 'was', 'born', 'there', 'was', 'a', 'plague', 'going', 'around', 'called', 'the', 'Bubonic', 'Plague', '.', 'This', 'is', 'also', 'known', 'as', 'Black', 'Death', 'because', 'it', 'killed', 'so', 'many', 'people', 'in', 'the', 'middle', 'ages', '.', 'It', 'supposedly', 'killed', 'about', 'one', 'out', 'of', 'every', 'seven', 'people', '.', 'Not', 'very', 'much', 'is', 'known', 'about', 'Shakespeare', '’', 's', 'early', 'years', 'in', 'life', ',', 'the', 'only', 'way', 'historians', 'found', 'about', 'his', 'early', 'life', 'were', 'based', 'on', 'church', 'records', ',', 'and', 'court', 'settlements', '.', 'It', 'was', 'thought', 'that'

## b. Remove punctuation from the text 

In [26]:
token_list1 = list(filter(lambda token: nltk.tokenize.punkt.PunktToken(token).is_non_punct, token_list))
print("Token list after removing stop words : ", token_list1[:20])
print("\nTotal tokens after removing stop words : ", len(token_list1))

Token list after removing stop words :  ['William', 'Shakespeare', 'was', 'born', 'in', 'Stratford-upon-Avon', 'on', 'April', '23', '1564', 'to', 'his', 'parents', 'Mary', 'Arden', 'and', 'John', 'Shakespeare', 'Shakespeare', 'was']

Total tokens after removing stop words :  564


## c. Remove stopwords from the text 

In [27]:
token_list2 = list(filter(lambda token: token not in stopwords.words('english'), token_list1))
print("Token list after removing stop words : ", token_list2[:20])
print("\nTotal tokens after removing stop words : ", len(token_list2))

Token list after removing stop words :  ['William', 'Shakespeare', 'born', 'Stratford-upon-Avon', 'April', '23', '1564', 'parents', 'Mary', 'Arden', 'John', 'Shakespeare', 'Shakespeare', 'third', 'child', 'eight', 'He', 'oldest', 'surviving', 'son']

Total tokens after removing stop words :  311


## d. Lemmatize the text

In [28]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
token_list3 = [lemmatizer.lemmatize(word) for word in token_list2 ]
print("Token list after Lemmatization : ", token_list3[:20])
print("\nTotal tokens after Lemmatization : ", len(token_list3))

Token list after Lemmatization :  ['William', 'Shakespeare', 'born', 'Stratford-upon-Avon', 'April', '23', '1564', 'parent', 'Mary', 'Arden', 'John', 'Shakespeare', 'Shakespeare', 'third', 'child', 'eight', 'He', 'oldest', 'surviving', 'son']

Total tokens after Lemmatization :  311


## e. Return processed text

In [29]:
a = str(token_list3)
a

"['William', 'Shakespeare', 'born', 'Stratford-upon-Avon', 'April', '23', '1564', 'parent', 'Mary', 'Arden', 'John', 'Shakespeare', 'Shakespeare', 'third', 'child', 'eight', 'He', 'oldest', 'surviving', 'son', 'time', 'Shakespeare', 'born', 'plague', 'going', 'around', 'called', 'Bubonic', 'Plague', 'This', 'also', 'known', 'Black', 'Death', 'killed', 'many', 'people', 'middle', 'age', 'It', 'supposedly', 'killed', 'one', 'every', 'seven', 'people', 'Not', 'much', 'known', 'Shakespeare', 'early', 'year', 'life', 'way', 'historian', 'found', 'early', 'life', 'based', 'church', 'record', 'court', 'settlement', 'It', 'thought', 'Shakespeare', 'got', 'education', 'grammar', 'school', 'called', 'King', 'Edward', 'VI', 'School', 'Stratford-upon-Avon', 'When', 'Shakespeare', 'eighteen', 'married', 'woman', 'eight', 'year', 'older', 'name', 'Anne', 'Hathaway', 'Together', 'three', 'child', 'The', 'first', 'girl', 'named', 'Susanna', 'two', 'year', 'later', 'twin', 'one', 'boy', 'name', 'Hamnet

## **4. Write a function that takes a list of strings and returns a list of processed string.**

In [ ]:
# Inout Strings

string = input()

In [ ]:
# Processing input strings

text_tokens = word_tokenize(string)

tokens_without_sw = [word for word in text_tokens if not word in stopwords.words()]

text = [lemmatizer.lemmatize(word) for word in tokens_without_sw ]
text

### 5. I understand the concept and purpose of unit test, but I am having some difficulties to apply in above NLP program. And I do not want to take more time to submit this assessment.